# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ommands.proto\x12\x08\x63ommands\"\xc9\x01\n\x0e\x43ontrolCommand\x12\x35\n\x07\x63ommand\x18\x01 \x01(\x0e\x32$.commands.ControlCommand.CommandType\x12\x1a\n\rmotorPosition\x18\x02 \x01(\x05H\x00\x88\x01\x01\"R\n\x0b\x43ommandType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05START\x10\x01\x12\x08\n\x04STOP\x10\x02\x12\t\n\x05RESET\x10\x03\x12\x16\n\x12SET_MOTOR_POSITION\x10\x04\x42\x10\n\x0e_motorPositionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONTROLCOMMAND']._serialized_start=29
  _globals['_CONTROLCOMMAND']._serialized_end=230
  _globals['_CONTROLCOMMAND_COMMANDTYPE']._serialized_start=130
  _globals['_CONTROLCOMMAND_COMMANDTYPE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
