# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: commands.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ommands.proto\x12\x08\x63ommands\"[\n\x0e\x43ontrolCommand\x12\n\n\x02id\x18\x01 \x01(\x05\x12&\n\x07\x63ommand\x18\x02 \x01(\x0e\x32\x15.commands.CommandType\x12\x15\n\rmotorPosition\x18\x03 \x01(\x05*R\n\x0b\x43ommandType\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x08\n\x04OPEN\x10\x01\x12\t\n\x05\x43LOSE\x10\x02\x12\t\n\x05RESET\x10\x03\x12\x16\n\x12SET_MOTOR_POSITION\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMANDTYPE']._serialized_start=121
  _globals['_COMMANDTYPE']._serialized_end=203
  _globals['_CONTROLCOMMAND']._serialized_start=28
  _globals['_CONTROLCOMMAND']._serialized_end=119
# @@protoc_insertion_point(module_scope)
