# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor_vals.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sensor_vals.proto\x12\x0bsensor_vals\"~\n\x06Sensor\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x0f\n\x02id\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x12\n\x05value\x18\x03 \x01(\x02H\x02\x88\x01\x01\x12\x15\n\x08switchOn\x18\x04 \x01(\x08H\x03\x88\x01\x01\x42\x07\n\x05_nameB\x05\n\x03_idB\x08\n\x06_valueB\x0b\n\t_switchOn\"2\n\nSensorData\x12$\n\x07sensors\x18\x01 \x03(\x0b\x32\x13.sensor_vals.Sensorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_vals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSOR']._serialized_start=34
  _globals['_SENSOR']._serialized_end=160
  _globals['_SENSORDATA']._serialized_start=162
  _globals['_SENSORDATA']._serialized_end=212
# @@protoc_insertion_point(module_scope)
